import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PeriodProvider } from '@/context/PeriodContext'


export const metadata: Metadata = {
    title: 'Histogram',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
  children: React.ReactNode
}) {
    return (
        <html lang="ru">
            <PeriodProvider>
                <body>{children}</body>
            </PeriodProvider>
        </html>
    )
}
